services:
  # Backend API service
  - type: web
    name: thai-municipality-form-v2
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: http://localhost:3000
      # Add MongoDB Atlas connection string when available
      - key: MONGODB_URI
        sync: false # This will be manually set in Render dashboard
